# Generated by Django 6.0.2 on 2026-04-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_id",
                    models.CharField(max_length=50, unique=True, verbose_name="项目ID"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="项目名称")),
                ("location", models.CharField(max_length=100, verbose_name="地点")),
                ("status", models.CharField(max_length=50, verbose_name="状态")),
                ("my_role", models.CharField(max_length=50, verbose_name="我的角色")),
                (
                    "interview_time",
                    models.DateField(blank=True, null=True, verbose_name="访谈时间"),
                ),
                ("member_count", models.IntegerField(default=0, verbose_name="成员数")),
                ("task_count", models.IntegerField(default=0, verbose_name="任务数")),
                (
                    "overdue_count",
                    models.IntegerField(default=0, verbose_name="逾期数"),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度")),
            ],
        ),
    ]
