# Generated by Django 6.0.2 on 2026-04-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="captain_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="支队长ID"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="项目描述"),
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="结束日期"),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="开始日期"),
        ),
    ]
