name: webapp
channels:
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
    - django
    - djangorestframework
    - gunicorn
    - psycopg2-binary
    - django-cors-headers
    - python-dotenv
